### ISSUE TITLE
arm上编译遇到以下错误，还望赐教

### ISSUE THREAD

**Issue by zhangzuoxing** [chenkui164/FastASR#1]
Makefile:37: obj/Vocab.d: No such file or directory
Makefile:37: obj/DecSelfAttn.d: No such file or directory
Makefile:37: obj/Decoder.d: No such file or directory
Makefile:37: obj/PositionEncoding.d: No such file or directory
Makefile:37: obj/ConvModule.d: No such file or directory
Makefile:37: obj/CTCDecode.d: No such file or directory
Makefile:37: obj/EmbedLayer.d: No such file or directory
Makefile:37: obj/LayerNorm.d: No such file or directory
Makefile:37: obj/DecEmbedLayer.d: No such file or directory
Makefile:37: obj/EncSelfAttn.d: No such file or directory
Makefile:37: obj/SubDecoder.d: No such file or directory
Makefile:37: obj/FeedForward.d: No such file or directory
Makefile:37: obj/Encoder.d: No such file or directory
Makefile:37: obj/Audio.d: No such file or directory
Makefile:37: obj/SubEncoder.d: No such file or directory
Makefile:37: obj/Model.d: No such file or directory
Makefile:37: obj/main.d: No such file or directory
Makefile:37: obj/WenetParams.d: No such file or directory
Makefile:37: obj/util.d: No such file or directory
g++ -c -o obj/Vocab.o ./src/Vocab.cpp -O3 -std=c++11   
g++ -c -o obj/DecSelfAttn.o ./src/DecSelfAttn.cpp -O3 -std=c++11   
./src/DecSelfAttn.cpp:3:19: fatal error: cblas.h: No such file or directory
 #include <cblas.h>
                   ^
compilation terminated.
make: *** [obj/DecSelfAttn.o] Error 1

**Comment by chenkui164** [comment]
前面几句“Makefile:37: obj/****No such file or directory“，这个是由于第一编译obj路径下没有对应的依赖文件而产生的警告，编译过一次后会自动生成，第二次编译就不会在提示了。

真正的错误是没有找到OpenBLAS这个库，需要确认下在ARM中OpenBLAS是否正确安装，按照教程我是把文件安装在/usr目录下，看一下这两个文件/usr/include/cblas.h和/usr/lib/libopenblas.so是否存在。如果OpenBLAS被安装到其它目录下，也可以修改Makefile，取消注释，然后根据OpenBLAS的安装位置修改对应的路径。

LDPATH+=-L/usr/local/lib
INCLUDEPATH+=-I /usr/local/include
