### ISSUE TITLE
paddlespeech asr -d

### ISSUE THREAD

**Issue by jkluo** [chenkui164/FastASR#10]
大佬，官方也出了 paddlespeech asr --input xx.job -d 批量模式，测试了一下 fastASR 和 paddlespeech 批量模式效率相差不大。

**Comment by chenkui164** [comment]
是的，因为paddlespeech是基于paddlepaddle构建的，如果计算机使用intel的芯片它会用MKL库加速，但是你使用的ARM芯片，所以底层应该也是Openblas，整个推理过程中最耗时的就是矩阵运算，其它的优化仅仅是锦上添花，我试图在优化过一些内容，但是仅仅提升了100ms的时间，所以我也没有什么好的办法。 @jkluo

**Comment by jkluo** [comment]
> 是的，因为paddlespeech是基于paddlepaddle构建的，如果计算机使用intel的芯片它会用MKL库加速，但是你使用的ARM芯片，所以底层应该也是Openblas，整个推理过程中最耗时的就是矩阵运算，其它的优化仅仅是锦上添花，我试图在优化过一些内容，但是仅仅提升了100ms的时间，所以我也没有什么好的办法。 @jkluo

确实，跟芯片关系很大。非常感谢大佬抽时间解答。
