### ISSUE TITLE
wenet模型适配

### ISSUE THREAD

**Issue by joinhe** [chenkui164/FastASR#18]
什么时候开放wenet模型的适配？

**Comment by znsoftm** [comment]
这里面的模型都是用wenet数据集训练的。
讲真的，k2模型目前的效果略好于wenet

**Comment by joinhe** [comment]
不一定，k2相对复杂，用更好的解码策略wenet的模型也能有很好的效果

**Comment by csukuangfj** [comment]
> k2相对复杂

请问是哪些地方复杂呢？安装、使用、代码，还是什么呢？

**Comment by joinhe** [comment]
安装，新手安装wenet几分钟，但是k2可能很久不一定能成功还需要人指导。

**Comment by csukuangfj** [comment]
> 安装，新手安装wenet几分钟，但是k2可能很久不一定能成功还需要人指导。

建议试试 
https://github.com/k2-fsa/sherpa-ncnn

---

所有依赖全部从源码安装。你网络快的话，1分钟，应该就可以编译完。生成的 binary 采用可以采用静态链接。
