### ISSUE TITLE
cmakelists support?

### ISSUE THREAD

**Issue by jinfagang** [chenkui164/FastASR#2]
hi. make doesn't quite support other platforms well, will consider add cmakelists build support?

**Comment by chenkui164** [comment]
This suggestion is very good, but the source code uses some linux platform-specific APIs, which are not compatible with windows and macos. My plan is to implement the streaming ASR function first, and then consider multi-platform. You will be notified as soon as the modification is completed.

**Comment by jinfagang** [comment]
@chenkui164  thanks, this is a very impressive work. For Multiplatform we can using some micro definition to handle it. I didn't have a raspberrypy but I'd like test it on my Mac. Will consider deploy it into Jetsonnano

**Comment by chenkui164** [comment]
The cpu of jetson nano is Quad-core ARM Cortex-A57, so it can be run directly according to the tutorial of Raspberry Pi. But the program does not use GPU, so it does not reflect the advantages of jetson nano @jinfagang

**Comment by chenkui164** [comment]
Hello, the cmake version of the program has been modified and is compatible with MacOS. thanks for using。 @jinfagang
