### ISSUE TITLE
段错误 (核心已转储)

### ISSUE THREAD

**Issue by NickSong1984** [chenkui164/FastASR#20]
./build/examples/k2_rnnt2_cli models/k2_rnnt2_cli/ zh.wav
Audio time is 4.996812 s. len is 79949
段错误 (核心已转储)

请问这个问题怎么解决？多谢！

**Comment by chenkui164** [comment]
在目录models/k2_rnnt2_cli中是不是没有wenet_params.bin这个文件，可以参考“**k2_rnnt2预训练模型下载**“这个章节完成转换，需要pytorch环境

**Comment by NickSong1984** [comment]
多谢您的回复，问题解决了
