### ISSUE TITLE
建议做一个python的直接安装用的轮子

### ISSUE THREAD

**Issue by znsoftm** [chenkui164/FastASR#22]
方便普通用户直接用pip 进行安装使用，里面可以包括转好的模型或者把模型分开包安装。

**Comment by chenkui164** [comment]
当时简单的查了一下，好像在电脑上要分别安装python3.6~3.10，还要考虑windows系统，感觉比较麻烦就先搁置了 @znsoftm

**Comment by znsoftm** [comment]
可以用源码的方式编译。在轮子安装时直接编译。反正这东东编译很方便的。

**Comment by znsoftm** [comment]
好多包都支持在安装轮子时编译源码。

**Comment by chenkui164** [comment]
哦，原来还可以这样，我看看要怎么弄

**Comment by znsoftm** [comment]
https://zhuanlan.zhihu.com/p/348417688

可以参考下这个

**Comment by csukuangfj** [comment]
建议使用pybind11.

**Comment by chenkui164** [comment]
> 建议使用pybind11.

嗯嗯，我也是看了k2和icefall的代码，他们都是用pybind11封装的，现在已经是用pybind11封装了。

**Comment by chenkui164** [comment]
已经通过github action 编译出各平台能用的二进制whl包，可通过pip install fastasr直接安装，不需要编译 @znsoftm
