### ISSUE TITLE
新功能建议：  可以白嫖个TTS模型。语音合成也是一种比较方便有用的功能

### ISSUE THREAD

**Issue by znsoftm** [chenkui164/FastASR#23]
如题：）

**Comment by cgisky1980** [comment]
是的呢，把 PaddleSpeech 撸一遍

**Comment by chenkui164** [comment]
谢谢，先不考虑了，年底了手头工作太忙了，实在抽不出时间

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/sherpa-onnx
推荐上面的项目

android apk 下载: https://k2-fsa.github.io/sherpa/onnx/tts/apk.html

colab demo: https://github.com/k2-fsa/colab/blob/master/sherpa-onnx/Text_to_speech_with_sherpa_onnx.ipynb

文档: https://k2-fsa.github.io/sherpa/onnx/tts

注： 支持 树莓派
