### ISSUE TITLE
windows运行好像是乱码

### ISSUE THREAD

**Issue by 591440833** [chenkui164/FastASR#24]
![image](https://user-images.githubusercontent.com/8233786/194605378-9ca91594-e5eb-48ff-8720-6738febd9044.png)

**Comment by chenkui164** [comment]
在cmd中输入CHCP 65001即可解决

**Comment by znsoftm** [comment]
vocab.txt默认是utf-8编码，兼容性比较好。chcp 65001 是用于切换默认编码为utf-8.
如果觉得麻烦，也可以把vocab.txt转码成gbk编码即可。

**Comment by 591440833** [comment]
按照提供方式修改，可以了，非常棒！

**Comment by 591440833** [comment]
你好：
&nbsp; 结果很好。如果能够把标点加上，就更完美。最近有这个方面的计划吗。


王焕松
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenkui164/FastASR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月8日(星期六) 中午11:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chenkui164/FastASR] windows运行好像是乱码 (Issue #24)





 
vocab.txt默认是utf-8编码，兼容性比较好。chcp 65001 是用于切换默认编码为utf-8.
 如果觉得麻烦，也可以把vocab.txt转码成gbk编码即可。
