### ISSUE TITLE
大视频好像有问题

### ISSUE THREAD

**Issue by 591440833** [chenkui164/FastASR#25]
链接：https://pan.baidu.com/s/13NM3UtRd1IBhQT13btdDBg 
提取码：f7as

**Comment by chenkui164** [comment]
你提供的这段音频文件是双声道，采样率是44100Hz所以不能直接使用，需要转换成16000Hz单声道的音频文件。
可以找工具转换一下。
比如：
ffmpeg -i 相声.wav -acodec pcm_s16le -ar 16000 -ac 1 sample.wav
