### ISSUE TITLE
pip install 问题

### ISSUE THREAD

**Issue by znsoftm** [chenkui164/FastASR#27]
我的机器上没有安装cmake 导致安装出错。建议检测一下cmake是否存在

**Comment by znsoftm** [comment]
提前安装好cmake和visualstudio的情况下，还常在windows 下安装成功。

**Comment by chenkui164** [comment]
已经通过github action 编译出各平台能用的二进制whl包，可通过pip install fastasr直接安装，不需要编译 @znsoftm
