### ISSUE TITLE
在windows10运行报错如下，请问如何解决？

### ISSUE THREAD

**Issue by billqu01** [chenkui164/FastASR#30]
D:\test\FastASR-main\out\build\x64-Debug\examples>k2_rnnt2_cli D:\test\FastASR-main\models\k2_rnnt2_cli long.wav
Audio time is 1781.655518 s. len is 28506489
Model initialization takes 2.993000s.
Result: " ** On entry to CTRSV  parameter number  1 had an illegal value
 ** On entry to CTRSV  parameter number  1 had an illegal value
 ** On entry to CTRSV  parameter number  1 had an illegal value
 ** On entry to CTRSV  parameter number  1 had an illegal value
 ** On entry to CTRSV  parameter number  1 had an illegal value
 ** On entry to CTRSV  parameter number  1 had an illegal value

**Comment by chenkui164** [comment]
看log应该是openblas异常了。我也分析不出来，试试编译release版本试试。如果只是简单试用的话，可以下载已编译好的版本

**Comment by billqu01** [comment]
谢谢。我把libopenblas.dll libfftw3f-3.dll 等拷贝到和k2_rnnt2_cli.exe一个文件夹内就没有报上面错误了。但是识别结果是乱码。
不知道怎么解决。请指教。谢谢。

D:\test\FastASR-main\out\build\x64-Debug\examples>k2_rnnt2_cli D:\test\FastASR-main\models\k2_rnnt2_cli long.wav
Audio time is 1781.655518 s. len is 28506489
Model initialization takes 2.990000s.
Result: "鍚紬鏈嬪弸鎮ㄤ笅闈㈠皢瑕佸惉鍒扮殑鏄笘鐣屾枃瀛﹀疂搴撲腑鐨勭弽鍝佹捣鏄庡▉鏈€浼樼鐨勪綔鍝佽€佷汉涓庢捣鍟婅€佷汉涓庢捣鍙戣〃浜庝竴涔濅簲浜屽勾璇ヤ功鍑虹増浠呭洓鍗佸叓灏忔椂灏遍攢閲忔儕浜哄綋骞村氨鑾峰緱浜嗘櫘鍒╃瓥鏂囧濂栦 竴涔濅簲鍥涘勾娴锋槑濞佸張鑾峰緱浜嗚璐濆皵鏂囧濂栨瘡涓€鍙ヨ瘽鍜屾瘡涓€娈佃惤閮借灏介噺鍐欏緱绠€娲佽繖鏄捣鏄庡▉鍐欎綔鐨勪俊鏉′箣涓€杩欎娇寰椾粬鐨勪綔鍝佹敼缂栨垚鐢靛奖鐨勬暟閲忔瘮浠讳綍鍏朵粬涓€浣嶈幏濂栬€呴兘瑕佸褰撲粬琚 甯冧负褰撳勾鐨勬櫘鍒╃瓥鏂囧濂栧緱涓绘椂璇勮鐣屼竴鑷寸О濂戒汉鍙互琚瘉鐏嵈涓嶅彲浠ヨ鎴樿儨娴锋槑濞佸湪鑰佷

**Comment by csukuangfj** [comment]
试试在命令行输入
```
D:\test\FastASR-main\out\build\x64-Debug\examples> CHCP 65001
```

然后输入
```
D:\test\FastASR-main\out\build\x64-Debug\examples>k2_rnnt2_cli D:\test\FastASR-main\models\k2_rnnt2_cli long.wav
```

**Comment by chenkui164** [comment]
可以参考#24，里面提供了两种方法@billqu01 。
同时谢谢，k2作者军哥帮忙解答 @csukuangfj 。

**Comment by billqu01** [comment]
非常感谢
