### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by v-yunbin** [chenkui164/FastASR#31]
`[ 90%] Built target PyFastASR
[ 92%] Building CXX object examples/CMakeFiles/paddlespeech_stream.dir/paddlespeech_stream.cpp.o
[ 93%] Linking CXX executable paddlespeech_stream
CMakeFiles/paddlespeech_stream.dir/paddlespeech_stream.cpp.o: In function `main':
paddlespeech_stream.cpp:(.text+0x1a7): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
paddlespeech_stream.cpp:(.text+0x1da): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
paddlespeech_stream.cpp:(.text+0x239): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
paddlespeech_stream.cpp:(.text+0x2c1): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
paddlespeech_stream.cpp:(.text+0x2e9): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
paddlespeech_stream.cpp:(.text+0x2fd): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
../lib/libfastasr.a(ModelImp.cpp.o): In function `paddlespeech::ModelImp::ModelImp(char const*, int)':
ModelImp.cpp:(.text+0x96): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
ModelImp.cpp:(.text+0xc5): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
ModelImp.cpp:(.text+0xee): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
ModelImp.cpp:(.text+0x11d): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
ModelImp.cpp:(.text+0x146): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
ModelImp.cpp:(.text+0x161): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
ModelImp.cpp:(.text+0x185): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
ModelImp.cpp:(.text+0x358): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
ModelImp.cpp:(.text+0x367): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
ModelImp.cpp:(.text+0x376): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
ModelImp.cpp:(.text+0x3ba): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
ModelImp.cpp:(.text+0x3df): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
../lib/libfastasr.a(ModelImp.cpp.o):ModelImp.cpp:(.text+0x464): more undefined references to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()' follow
../lib/libfastasr.a(ModelImp.cpp.o): In function `kaldi2::ModelImp::ModelImp(char const*, int)':
ModelImp.cpp:(.text+0x6e): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
ModelImp.cpp:(.text+0x97): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
ModelImp.cpp:(.text+0xc6): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
ModelImp.cpp:(.text+0xe1): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
ModelImp.cpp:(.text+0x113): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
ModelImp.cpp:(.text+0x139): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
ModelImp.cpp:(.text+0x15f): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
ModelImp.cpp:(.text+0x177): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
ModelImp.cpp:(.text+0x192): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
ModelImp.cpp:(.text+0x1ef): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
ModelImp.cpp:(.text+0x300): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
ModelImp.cpp:(.text+0x30f): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
ModelImp.cpp:(.text+0x326): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
ModelImp.cpp:(.text+0x346): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
ModelImp.cpp:(.text+0x374): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
../lib/libfastasr.a(ModelImp.cpp.o):ModelImp.cpp:(.text+0x391): more undefined references to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()' follow
../lib/libfastasr.a(ModelImp.cpp.o): In function `kaldi2::ModelImp::forward_chunk[abi:cxx11](float*, int, int)':
ModelImp.cpp:(.text+0x8dd): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
../lib/libfastasr.a(ModelImp.cpp.o): In function `kaldi2::ModelImp::rescoring[abi:cxx11]()':
ModelImp.cpp:(.text+0x950): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
../lib/libfastasr.a(Vocab.cpp.o): In function `Vocab::Vocab(char const*)':
Vocab.cpp:(.text+0x52): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
Vocab.cpp:(.text+0x67): undefined reference to `std::basic_ios<char, std::char_traits<char> >::operator bool() const'
Vocab.cpp:(.text+0x84): undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
Vocab.cpp:(.text+0x99): undefined reference to `std::basic_ios<char, std::char_traits<char> >::operator bool() const'
Vocab.cpp:(.text+0xc7): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
Vocab.cpp:(.text+0xea): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
../lib/libfastasr.a(Vocab.cpp.o): In function `Vocab::vector2string[abi:cxx11](std::vector<int, std::allocator<int> >)':
Vocab.cpp:(.text+0x181): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)'
Vocab.cpp:(.text+0x203): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
Vocab.cpp:(.text+0x235): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::str() const'
Vocab.cpp:(.text+0x245): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
Vocab.cpp:(.text+0x259): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
../lib/libfastasr.a(Vocab.cpp.o): In function `void __gnu_cxx::new_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::construct<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
Vocab.cpp:(.text._ZN9__gnu_cxx13new_allocatorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE9constructIS6_JRKS6_EEEvPT_DpOT0_[_ZN9__gnu_cxx13new_allocatorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE9constructIS6_JRKS6_EEEvPT_DpOT0_]+0x43): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../lib/libfastasr.a(Vocab.cpp.o): In function `void __gnu_cxx::new_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::destroy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
Vocab.cpp:(.text._ZN9__gnu_cxx13new_allocatorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE7destroyIS6_EEvPT_[_ZN9__gnu_cxx13new_allocatorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE7destroyIS6_EEvPT_]+0x18): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
../lib/libfastasr.a(Vocab.cpp.o): In function `void std::_Destroy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
Vocab.cpp:(.text._ZSt8_DestroyINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEvPT_[_ZSt8_DestroyINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEvPT_]+0x14): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
../lib/libfastasr.a(Vocab.cpp.o): In function `void std::_Construct<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)':
Vocab.cpp:(.text._ZSt10_ConstructINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEJS5_EEvPT_DpOT0_[_ZSt10_ConstructINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEJS5_EEvPT_DpOT0_]+0x38): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)'
../lib/libfastasr.a(util.cpp.o): In function `pathAppend(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
util.cpp:(.text+0x381): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
util.cpp:(.text+0x38d): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::length() const'
util.cpp:(.text+0x3a0): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator[](unsigned long) const'
util.cpp:(.text+0x3bf): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator+=(char)'
util.cpp:(.text+0x3fb): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
util.cpp:(.text+0x40c): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
../lib/libfastasr.a(util.cpp.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
util.cpp:(.text._ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EERKS8_SA_[_ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EERKS8_SA_]+0x24): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
util.cpp:(.text._ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EERKS8_SA_[_ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EERKS8_SA_]+0x37): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
util.cpp:(.text._ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EERKS8_SA_[_ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EERKS8_SA_]+0x48): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
../third_party/webrtc/libwebrtcvad.a(checks.cc.o): In function `(anonymous namespace)::AppendFormat(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, char const*, ...)':
checks.cc:(.text+0xeb): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::size() const'
checks.cc:(.text+0x117): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::resize(unsigned long)'
checks.cc:(.text+0x13c): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator[](unsigned long)'
../third_party/webrtc/libwebrtcvad.a(checks.cc.o): In function `rtc::webrtc_checks_impl::ParseArg(__va_list_tag (*) [1], rtc::webrtc_checks_impl::CheckArgType const**, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
checks.cc:(.text+0x51d): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*)'
checks.cc:(.text+0x577): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
checks.cc:(.text+0x5ec): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*)'
../third_party/webrtc/libwebrtcvad.a(checks.cc.o): In function `rtc::webrtc_checks_impl::FatalLog(char const*, int, char const*, rtc::webrtc_checks_impl::CheckArgType const*, ...)':
checks.cc:(.text+0x6a4): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
checks.cc:(.text+0x713): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
checks.cc:(.text+0x722): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
checks.cc:(.text+0x789): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
checks.cc:(.text+0x79b): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
checks.cc:(.text+0x7cb): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
checks.cc:(.text+0x7da): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
checks.cc:(.text+0x7f2): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*)'
checks.cc:(.text+0x827): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
checks.cc:(.text+0x885): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
checks.cc:(.text+0x894): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
checks.cc:(.text+0x8a8): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/CMakeFiles/paddlespeech_stream.dir/build.make:99: examples/paddlespeech_stream] Error 1
make[1]: *** [CMakeFiles/Makefile2:238: examples/CMakeFiles/paddlespeech_stream.dir/all] Error 2
`

**Comment by chenkui164** [comment]
看报错应该是C++11链接不上，编译的环境是什么？GCC和G++的版本是多少？

**Comment by v-yunbin** [comment]
> 看报错应该是C++11链接不上，编译的环境是什么？GCC和G++的版本是多少？

linux环境Centos 7.9 ，g++和gcc都是8.2.0，

**Comment by csukuangfj** [comment]
试试命令行加个
```
g++ -D _GLIBCXX_USE_CXX11_ABI=0
```

`_GLIBCXX_USE_CXX11_ABI` 要么都用0, 要么都用1

**Comment by chenkui164** [comment]
根据这篇文章https://www.cnblogs.com/lukybee/p/11846889.html，
试试增加个宏定义，
cmake -DFASTASR_BUILD_PYTHON_MODULE=ON -D_GLIBCXX_USE_CXX11_ABI=1 ..
目前也就只能这样试试了

**Comment by v-yunbin** [comment]
> 根据这篇文章[https://www.cnblogs.com/lukybee/p/11846889.html，](https://www.cnblogs.com/lukybee/p/11846889.html%EF%BC%8C) 试试增加个宏定义， cmake -DFASTASR_BUILD_PYTHON_MODULE=ON -D_GLIBCXX_USE_CXX11_ABI=1 .. 目前也就只能这样试试了

找到原因了 openblas我用gcc4.8.5编译的，我把gcc切换到4.8.5，make成功了。然而使用python程序解码的时候报错。。：
```
Audio time is 4.9968125s. len is 79949.
Segmentation fault (core dumped)

```

**Comment by chenkui164** [comment]
看一下在文件夹models/k2_rnnt2_cli/ 下面是否有模型权重文件wenet_params.bin，没有的话需要根据教程转换一下

**Comment by v-yunbin** [comment]
> wenet_params.bin

wenet_params.bin这个我自己转换了，放在了build目录下，我把他移动到了models/paddlespeech_cli。还是同样的错

**Comment by v-yunbin** [comment]
> 看一下在文件夹models/k2_rnnt2_cli/ 下面是否有模型权重文件wenet_params.bin，没有的话需要根据教程“k2_rnnt2预训练模型下载”章节转换一下，也可以从百度网盘下载转换好的模型 百度网盘: https://pan.baidu.com/s/1irtnZthexSjQlRF6F8jRPQ 提取码: 5it6

可以了不好意思，模型路径没放对，kaldi2后续会增加online解码吗，我看k2更新了online模型
[![16A332DC](https://user-images.githubusercontent.com/38179632/204509873-eaadbf19-e62c-4eee-91fc-06b7bf3d2195.png)](https://huggingface.co/luomingshuang/icefall_asr_wenetspeech_pruned_transducer_stateless5_streaming)

**Comment by chenkui164** [comment]
可能不太会增加了，整个推理过程是纯手动实现的，从仿真到C++的实现，要一个模型要花一个多月的时间，最近本职工作任务比较重，抽不出太多时间来弄了

**Comment by v-yunbin** [comment]
> 可能不太会增加了，整个推理过程是纯手动实现的，从仿真到C++的实现，一个模型要花一个多月的时间，最近本职工作任务比较重，抽不出太多时间来弄了

行吧，我关了

**Comment by v-yunbin** [comment]
@chenkui164 再问一个问题哈，k2的stateless5模型可以直接使用吗？
