### ISSUE TITLE
windows下编译出错，

### ISSUE THREAD

**Issue by xbsdsongnan** [chenkui164/FastASR#32]
由于找不到libfftw3f-3.dll,无法继续执行代码。重新安装程序可能会解决此问题，如何解决

**Comment by xbsdsongnan** [comment]
线程 0x7cb8 已退出，返回值为 3221225781 (0xc0000135)。
线程 0x9fd4 已退出，返回值为 3221225781 (0xc0000135)。
程序“[66476] k2_rnnt2_cli.exe”已退出，返回值为 3221225781 (0xc0000135) '未找到依赖 dll'。

**Comment by chenkui164** [comment]
你这个是直接在VS里运行的吧，看log已经是编译正确了。用cmd或者powershell直接运行，工作目录在FastASR/out/build/x64-Release/examples下，参考教程中的命令行执行

**Comment by xbsdsongnan** [comment]
遇到音频问题会出现弹窗提示exe异常错误，但是没有具体错误提示，如何解决呢

**Comment by chenkui164** [comment]
音频是16k单声道的wav文件。代码里面没有做检测，所以调用前需要人工保证音频正确

**Comment by xbsdsongnan** [comment]
Audio time is 2.377063 s. len is 38033
Model initialization takes 0.138000s.
frame end > max_len!!!!!!!
Result: "
输入一个音频，出现这个，耳朵可以听，但是没结果

**Comment by chenkui164** [comment]
把音频传到百度网盘上，我看看
