### ISSUE TITLE
持续报这个错误

### ISSUE THREAD

**Issue by David19970306** [chenkui164/FastASR#35]
/home/opt/compiler/gcc-8.2/gcc-8.2/include/c++/8.2.0/cstdlib:137:11: error: ‘::at_quick_exit’ has not been declared
   using ::at_quick_exit;
           ^~~~~~~~~~~~~
/home/opt/compiler/gcc-8.2/gcc-8.2/include/c++/8.2.0/cstdlib:160:11: error: ‘::quick_exit’ has not been declared
   using ::quick_exit;

**Comment by cgisky1980** [comment]
升级下你gcc版本呗
