### ISSUE TITLE
期待能出品一个fastTTS

### ISSUE THREAD

**Issue by xiongfeigood** [chenkui164/FastASR#37]
目前arm的tts几乎没有开源的项目，也没有几个高效的项目。
期待大神能出品一个TTS的项目！

**Comment by cgisky1980** [comment]
tts 开源的很多，arm 开发板能跑出实时效果的的确没有。白嫖了微软的，别说开源的了，那些大厂的云服务的都不香了。看好vits

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/sherpa-onnx
推荐上面的项目

android apk 下载: https://k2-fsa.github.io/sherpa/onnx/tts/apk.html

colab demo: https://github.com/k2-fsa/colab/blob/master/sherpa-onnx/Text_to_speech_with_sherpa_onnx.ipynb

文档:  https://k2-fsa.github.io/sherpa/onnx/tts

---

注： 支持 树莓派
