### ISSUE TITLE
请问是否支持多线程并发

### ISSUE THREAD

**Issue by Tian14267** [chenkui164/FastASR#39]
大神好，请问这个FastASR是否支持多线程并发服务？

**Comment by chenkui164** [comment]
可以的，每个线程都单独new一个实例即可

**Comment by Tian14267** [comment]
> 可以的，每个线程都单独new一个实例即可

@chenkui164 大神你好，我使用`conformer_online_wenetspeech-zh-16k模型测试` 进行python版本的**流式部署**和测试发现，并不支持并发啊。并发时间和并发路数成完全的正比~比如一个并发调用耗时5s，两个并发调用就耗时10s。。。我启动了多个模型预测器和实例。

**Comment by chenkui164** [comment]
是的，在推理过程中已经多线程推理了。并发只会抢占CPU的资源，降低单个实例推理速度。

**Comment by Tian14267** [comment]
> 是的，在推理过程中已经多线程推理了。并发只会抢占CPU的资源，降低单个实例推理速度。

@chenkui164 大神你好。如果我想实现python的并发调用？可以用这个项目实现吗？流式识别部署，并发调用。调用耗时不会显著增长的那种~~

**Comment by chenkui164** [comment]
抱歉，并没有更好的办法
