### ISSUE TITLE
支持GPU加速

### ISSUE THREAD

**Issue by dtx525942103** [chenkui164/FastASR#4]
这是开源的最好的ASR，比K2,WENET,PADDLE SPEECH都好用，期望能支持GPU加速

**Comment by chenkui164** [comment]
感谢使用，只是目前我在做模型量化和压缩的工作，这样可以让算法消耗更少的内存和获得更快的执行速度。支持GPU加速的工作也在调研当中，NVIDIA的GPU因为有成熟的CUDA库所以比较容易实现，但是像ARM上的GPU如何加速，仍需调研。

**Comment by wentlei** [comment]
> 感谢使用，只是目前我在做模型量化和压缩的工作，这样可以让算法消耗更少的内存和获得更快的执行速度。支持GPU加速的工作也在调研当中，NVIDIA的GPU因为有成熟的CUDA库所以比较容易实现，但是像ARM上的GPU如何加速，仍需调研。 @dtx525942103

大佬，NVIDIA的GPU支持有相关实例吗？

**Comment by chenkui164** [comment]
没有实现，目前并不支持GPU。
