### ISSUE TITLE
parafomer model decoding error

### ISSUE THREAD

**Issue by v-yunbin** [chenkui164/FastASR#50]
```
Audio time is 201.13125s. len is 3218100.
Model initialization takes 3.3s.
Traceback (most recent call last):
  File "examples/paraformer_cli.py", line 24, in <module>
    result = p.forward(data)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 2: invalid start byte
```

**Comment by chenkui164** [comment]
是这样的Python的里面没有做vad，所以输入太长会导致模型崩溃

**Comment by v-yunbin** [comment]
> 是这样的Python的里面没有做vad，所以输入太长会导致内存溢出，从而模型崩溃

这块儿我加了VAD依然报那个错。
```
  File "examples/paraformer_cli.py", line 34, in <module>
    result = p.forward(partdata_numpy)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 2: invalid start byte
```

**Comment by chenkui164** [comment]
把音频提交上，让我debug一下

**Comment by v-yunbin** [comment]
> 把音频提交上，让我debug一下
公司电脑限制往上传，上传不上来。。。其实就是一个wav音频30s
share.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 16000 Hz

**Comment by chenkui164** [comment]
是在window下么？

**Comment by v-yunbin** [comment]
> 是在window下么？

linux上面，之前在windows试了下没装上，找不到fastasr包。

**Comment by chenkui164** [comment]
我这里都是正常的，中文，英文，中英文
![image](https://user-images.githubusercontent.com/34813030/219618210-9b9f0411-116e-477b-aa0d-daff13b12fb4.png)

**Comment by chenkui164** [comment]
我win10系统，刚试过我直接pip install fastasr就能用，没有异常

**Comment by v-yunbin** [comment]
> 我这里都是正常的，中文，英文，中英文 ![image](https://user-images.githubusercontent.com/34813030/219618210-9b9f0411-116e-477b-aa0d-daff13b12fb4.png)

windows刚装上了，是可以的，liunux卸载了重装还不行。。。。。奇怪

**Comment by chenkui164** [comment]
试试重新下载模型里面的vocab.txt，我也不知道原因在哪了
