### ISSUE TITLE
找不到libopenblas库

### ISSUE THREAD

**Issue by andyweiqiu** [chenkui164/FastASR#57]
安装好依赖，并且也成功编译出whl文件，将fastasr安装到python环境中，但是执行推理的时候，出现下面的错误：
(asr) [qiuwei@dt_dev_gpu_3282 FastASR]$ python examples/paraformer_cli.py /data2/qiuwei/asr/FastASR/models/paraformer_cli /data2/qiuwei/asr/FastASR/models/paraformer_cli/zh.wav
Traceback (most recent call last):
  File "examples/paraformer_cli.py", line 1, in <module>
    import fastasr
  File "/home/qiuwei/anaconda3/envs/asr/lib/python3.8/site-packages/fastasr/__init__.py", line 1, in <module>
    from _fastasr import Model
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory

请问这有可能是什么问题？

**Comment by chenkui164** [comment]
openblas的库没找到，可能是conda的原因，试试在conda环境中安装
pip install pylib-openblas
pip install pylib-fftw3
或者手动配置下LD_LIBRARY_PATH估计也行

**Comment by andyweiqiu** [comment]
> openblas的库没找到，可能是conda的原因，试试在conda环境中安装 pip install pylib-openblas pip install pylib-fftw3 或者手动配置下LD_LIBRARY_PATH估计也行

好的，我试试，非常感谢！
