### ISSUE TITLE
[feature request] 楼主可以画一个拆分的结构图吗？

### ISSUE THREAD

**Issue by jinfagang** [chenkui164/FastASR#6]
原版的确比较复杂，尤其是到出道onnx之后，很多浇水算子，也没有了最原始的结构信息。

楼主是否可以考虑画一个 FastASR里面的结构图，例如讲那些模块合并了，做了哪些拆分。最好是能匹配上原版python对应的部分

**Comment by chenkui164** [comment]
conformer模型结构可以参考论文https://arxiv.org/pdf/2005.08100.pdf，我并没有进行模块合并与拆分，基本只是复现了一下论文中的推理过程而已。
