### ISSUE TITLE
stream模式处理长时间语音时出错

### ISSUE THREAD

**Issue by opentld** [chenkui164/FastASR#64]
问题出在这一句：
![image](https://github.com/chenkui164/FastASR/assets/21096515/b38b93f5-22cb-4506-9fe7-268aca840a92)
报0x0000005异常，读取了禁止读取的内存
![image](https://github.com/chenkui164/FastASR/assets/21096515/887b808d-fb01-4d2d-8759-bc8d54e9b6cc)
每次都是sum累加到665040就出错，是音频问题？还是有bug了？
@chenkui164 大佬请关注一下

**Comment by chenkui164** [comment]
stream模式没做VAD,语音太长了，会导致内存溢出。

**Comment by csukuangfj** [comment]
stream 模式，是不是可以支持任意长的音频？（只要他们不是一次性送进来的，理论上讲，需要 cache 的数据是一定的，不会 oom 吧?)

**Comment by opentld** [comment]
> stream模式没做VAD,语音太长了，会导致内存溢出。

过一段时间，就mm->reset 怎么样？会解决吗？

**Comment by chenkui164** [comment]
> > stream模式没做VAD,语音太长了，会导致内存溢出。
> 
> 过一段时间，就mm->reset 怎么样？会解决吗？

应该不行，改起来比较麻烦，所以就没给stream模式加VAD。可以试试[sherpa-ncnn](https://github.com/k2-fsa/sherpa-ncnn)和[sherpa-onnx](https://github.com/k2-fsa/sherpa-onnx)，里面有最先进的模型，而且支持会更好

**Comment by chenkui164** [comment]
> stream 模式，是不是可以支持任意长的音频？（只要他们不是一次性送进来的，理论上讲，需要 cache 的数据是一定的，不会 oom 吧?)

paddlespeech的模型，cache是累积的，不是一个固定的窗口，所以会溢出。

**Comment by csukuangfj** [comment]
> > stream 模式，是不是可以支持任意长的音频？（只要他们不是一次性送进来的，理论上讲，需要 cache 的数据是一定的，不会 oom 吧?)
> 
> paddlespeech的模型，cache是累积的，不是一个固定的窗口，所以会溢出。

这种设计是不是不能支持长时间持续运行？

**Comment by chenkui164** [comment]
> > > stream 模式，是不是可以支持任意长的音频？（只要他们不是一次性送进来的，理论上讲，需要 cache 的数据是一定的，不会 oom 吧?)
> > 
> > 
> > paddlespeech的模型，cache是累积的，不是一个固定的窗口，所以会溢出。
> 
> 这种设计是不是不能支持长时间持续运行？

恩，不支持。只是支持每句话的流式，不是每段话的流式。

**Comment by opentld** [comment]
> > > stream模式没做VAD,语音太长了，会导致内存溢出。
> > 
> > 
> > 过一段时间，就mm->reset 怎么样？会解决吗？
> 
> 应该不行，改起来比较麻烦，所以就没给stream模式加VAD。可以试试[sherpa-ncnn](https://github.com/k2-fsa/sherpa-ncnn)和[sherpa-onnx](https://github.com/k2-fsa/sherpa-onnx)，里面有最先进的模型，而且支持会更好

试了一下，reset是可以的，只是会丢字...

**Comment by csukuangfj** [comment]
> > > > stream 模式，是不是可以支持任意长的音频？（只要他们不是一次性送进来的，理论上讲，需要 cache 的数据是一定的，不会 oom 吧?)
> > > 
> > > 
> > > paddlespeech的模型，cache是累积的，不是一个固定的窗口，所以会溢出。
> > 
> > 
> > 这种设计是不是不能支持长时间持续运行？
> 
> 恩，不支持。只是支持每句话的流式，不是每段话的流式。

模型是这么设计的，还是他们的实现有这个限制？ 可以不可以改掉呢？

**Comment by opentld** [comment]
> > > stream模式没做VAD,语音太长了，会导致内存溢出。
> > 
> > 
> > 过一段时间，就mm->reset 怎么样？会解决吗？
> 
> 应该不行，改起来比较麻烦，所以就没给stream模式加VAD。可以试试[sherpa-ncnn](https://github.com/k2-fsa/sherpa-ncnn)和[sherpa-onnx](https://github.com/k2-fsa/sherpa-onnx)，里面有最先进的模型，而且支持会更好

![image](https://github.com/chenkui164/FastASR/assets/21096515/098a6709-97f7-4861-a134-b88108151090)

其实是可以的，只需要一点小编程技巧 ；)

**Comment by LDBS666** [comment]
> > > > stream模式没做VAD,语音太长了，会导致内存溢出。
> > > 
> > > 
> > > 过一段时间，就mm->reset 怎么样？会解决吗？
> > 
> > 
> > 应该不行，改起来比较麻烦，所以就没给stream模式加VAD。可以试试[sherpa-ncnn](https://github.com/k2-fsa/sherpa-ncnn)和[sherpa-onnx](https://github.com/k2-fsa/sherpa-onnx)，里面有最先进的模型，而且支持会更好
> 
> ![image](https://private-user-images.githubusercontent.com/21096515/238377529-098a6709-97f7-4861-a134-b88108151090.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMjU0NTMsIm5iZiI6MTcwMjAyNTE1MywicGF0aCI6Ii8yMTA5NjUxNS8yMzgzNzc1MjktMDk4YTY3MDktOTdmNy00ODYxLWExMzQtYjg4MTA4MTUxMDkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDA4NDU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzYTNhNmZlOTc1YWFjODBhNzU0YjdjZDM2ZTlhNDY5MjQ2NDc5ODE5ZDFmMGY3ZWYwMmRlOGY4ZTA2YzhjNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pYqk3vDFTY4wD_LnD9kJsdPh-aV8rTiBBveLoC973Fk)
> 
> 其实是可以的，只需要一点小编程技巧 ；)

什么小编程技巧呀？语音切片么？
