### ISSUE TITLE
fatal error: 'fftw3.h' file not found

### ISSUE THREAD

**Issue by jkluo** [chenkui164/FastASR#7]
brew install fftw 安装好后，make的时候还是提示 fatal error: 'fftw3.h' file not found。 

ll /usr/local/include 
total 296
drwxr-xr-x  7 root  wheel    224  8  8 14:06 ./
drwxr-xr-x  6 root  wheel    192  8  8 14:06 ../
-rw-r--r--  1 root  wheel   2447  8  8 14:06 fftw3.f
-rw-r--r--  1 root  wheel  55032  8  8 14:06 fftw3.f03
-rw-r--r--  1 root  wheel  31986  8  8 14:06 fftw3.h
-rw-r--r--  1 root  wheel  27203  8  8 14:06 fftw3l.f03
-rw-r--r--  1 root  wheel  25902  8  8 14:06 fftw3q.f03

**Comment by chenkui164** [comment]
修改一下[CMakeLists.txt](https://github.com/chenkui164/FastASR/blob/main/lib/CMakeLists.txt)

找到fftw的include的目录和lib目录，修改成本机所在位置

target_include_directories(fastasr PUBLIC "/usr/local/opt/fftw/include")
target_link_directories(fastasr PUBLIC "/usr/local/opt/fftw/lib")

找到openblas的include的目录和lib目录，修改成本机所在位置

target_include_directories(fastasr PUBLIC "/usr/local/opt/openblas/include")
target_link_directories(fastasr PUBLIC "/usr/local/opt/openblas/lib")

**Comment by jkluo** [comment]
在[CMakeLists.txt] 上加了路径后解决了。

cmake_minimum_required(VERSION 3.10)

set (CMAKE_CXX_STANDARD 11)

project(FastASR)


add_subdirectory(lib)
add_subdirectory(examples)

target_include_directories(fastasr PUBLIC "/opt/homebrew/opt/fftw/include")
target_link_directories(fastasr PUBLIC "/opt/homebrew/opt/fftw/lib")

target_include_directories(fastasr PUBLIC "/opt/homebrew/opt/openblas/include")
target_link_directories(fastasr PUBLIC "/opt/homebrew/opt/openblas/lib")
