### ISSUE TITLE
无法正确转换成文字

### ISSUE THREAD

**Issue by flyingdouers** [chenkui164/FastASR#76]
1、使用 k2_rnnt2_cli中的模型
2、语音是用麦克风直接录制的
3、本地运行
4、网盘是测试用的wav文件，谢谢！
链接：https://pan.baidu.com/s/1f4RZRSs1u-atZAVtNDbmYw 
提取码：s555

**Comment by chenkui164** [comment]
你好，这个音频是双声道的，需要用工具转换成单声道，采样率16k是正确的。

**Comment by flyingdouers** [comment]
你好，非常感谢，已经可以识别了。我现在的字典库只需要50个汉字，bin模型能变的小点么？如果可以，我应该怎么做
