### ISSUE TITLE
zsh: segmentation fault

### ISSUE THREAD

**Issue by jkluo** [chenkui164/FastASR#8]
./build/examples/fastasr_cli_c cli/ ~/Downloads/20220308.wav                        
Audio time is 254.849060 s.
Model initialization takes 0.346016s
zsh: segmentation fault  ./build/examples/fastasr_cli_c cli/ ~/Downloads/20220308.wav

**Comment by jkluo** [comment]
请问是不是音频时间问题呢？ 测试的音频是跑起来了

**Comment by chenkui164** [comment]
对输入的音频是有要求的，必须是wav格式，并且采样率为16000,长度能超过50s @jkluo

**Comment by jkluo** [comment]
> 对输入的音频是有要求的，必须是wav格式，并且采样率为16000,长度能超过50s @jkluo

@chenkui164 如果我音频长度超过50s，除了将长音频分割成多个 小于50s的短音频外，还有其他方法吗？修改源码的音频长度限制可以吗？

**Comment by chenkui164** [comment]
这是不可行的，要通过算法将长的音频分割为每句话。这是由conformer模型本身的特点决定的。

**Comment by jkluo** [comment]
> @jkluo 这是不可行的，要通过算法将长的音频分割为每句话。这是由conformer模型本身的特点决定的。

好的，感谢作者解答。 另外我看项目中有提到  **本项目最终生成的是动态库libfastasr.so和静态库libfastasr.a文件，方便用户的调用**  ， 我在目录下没有找到 这两个问题，请教一下这两个文件要怎么使用呢？

**Comment by chenkui164** [comment]
在目录XXX/FastASR/build/lib里面，有静态库libfastasr.a，我试了下动态库好像没有生成，需要改一下cmakefile了。

这是一个C和C++的库，程序示例可以参考XXX/FastASR/examples/中，使用方法很简单。

**Comment by chenkui164** [comment]
可以试试，最新版的fastasr，已经支持长语音了。 @jkluo
