### ISSUE TITLE
测试报错segmentation fault

### ISSUE THREAD

**Issue by Duanexiao** [chenkui164/FastASR#9]
使用的示例下载的zh,wav文件

./build/examples/fastasr_cli cli/ zh.wav

fastasr_cli[21567]: segfault at 0 ip           (null) sp 00007fff99249418 error 14 in fastasr_cli[400000+27000]

**Comment by jkluo** [comment]
> 使用的示例下载的zh,wav文件
> 
> ./build/examples/fastasr_cli cli/ zh.wav
> 
> fastasr_cli[21567]: segfault at 0 ip (null) sp 00007fff99249418 error 14 in fastasr_cli[400000+27000]

我的执行没这个问题

**Comment by Duanexiao** [comment]
> 

啥环境部署的？服务器还是正常的笔记本？

**Comment by jkluo** [comment]
> > 
> 
> 啥环境部署的？服务器还是正常的笔记本？

mac  M1 上

**Comment by Duanexiao** [comment]
我直接用的centos，估计是不能在centos上跑吧

**Comment by chenkui164** [comment]
你看一下zh.wav的路径对么？ @Duanexiao ，centos应该是没有问题的

**Comment by jkluo** [comment]
> centos应该是没有问题的

centos上也能跑起来的。

**Comment by Duanexiao** [comment]
> 

按照文档操作的，应该是centos有什么问题。我换ubuntu就Ok
